package index

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func assistantMsg(text string) string {
	return `{"type":"message","message":{"role":"assistant","content":[{"type":"text","text":"` + text + `"}]}}`
}

func TestSessionRowRecordsHostAndReply(t *testing.T) {
	dir := writeCorpus(t, map[string][]string{
		"s1": {userMsg("how do I center a div"), assistantMsg("use flexbox")},
	})
	db := openTest(t)
	if _, err := Build(context.Background(), db, BuildOptions{Dirs: []string{dir}}); err != nil {
		t.Fatal(err)
	}

	var host, preview, reply string
	var title *string
	err := db.SQL().QueryRow(
		`SELECT host, preview, reply, title FROM sessions WHERE id = 's1'`).
		Scan(&host, &preview, &reply, &title)
	if err != nil {
		t.Fatal(err)
	}

	// host is machine-local metadata that makes indexes from several machines
	// distinguishable once they can be merged.
	if host == "" {
		t.Error("host not recorded")
	}
	if preview != "how do I center a div" {
		t.Errorf("preview = %q", preview)
	}
	// The list shows three lines; reply keeps the third from repeating the
	// second while titles are still a fallback.
	if reply != "use flexbox" {
		t.Errorf("reply = %q, want the first assistant message", reply)
	}
	if title != nil {
		t.Errorf("title = %q, want NULL until the summarizing pass runs", *title)
	}
}

// Titles are generated by a separate, expensive pass. Sessions are append-only
// and get reindexed every time they grow by a message, so a reindex that
// clobbered the title would mean re-summarizing a live session continuously.
func TestTitleSurvivesReindex(t *testing.T) {
	dir := writeCorpus(t, map[string][]string{"s1": {userMsg("first question")}})
	db := openTest(t)
	if _, err := Build(context.Background(), db, BuildOptions{Dirs: []string{dir}}); err != nil {
		t.Fatal(err)
	}
	if _, err := db.SQL().Exec(`UPDATE sessions SET title = ? WHERE id = 's1'`, "A good title"); err != nil {
		t.Fatal(err)
	}

	// Append to the session, the way pi does, and reindex.
	p := filepath.Join(dir, "--Users-me-code-proj--", "s1.jsonl")
	f, err := os.OpenFile(p, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.WriteString(userMsg("a second question") + "\n"); err != nil {
		t.Fatal(err)
	}
	f.Close()
	if err := os.Chtimes(p, time.Now(), time.Now().Add(time.Second)); err != nil {
		t.Fatal(err)
	}

	pr, err := Build(context.Background(), db, BuildOptions{Dirs: []string{dir}})
	if err != nil {
		t.Fatal(err)
	}
	if pr.Indexed != 1 {
		t.Fatalf("indexed = %d, want the changed session reindexed", pr.Indexed)
	}

	var title *string
	var nMsgs int
	if err := db.SQL().QueryRow(
		`SELECT title, n_msgs FROM sessions WHERE id = 's1'`).Scan(&title, &nMsgs); err != nil {
		t.Fatal(err)
	}
	if title == nil || *title != "A good title" {
		t.Errorf("title = %v, want it preserved across a reindex", title)
	}
	if nMsgs != 2 {
		t.Errorf("n_msgs = %d, want 2: the rest of the row must still update", nMsgs)
	}
}
